/*******************************************************************************************************
 *************************************** FRONTEND AUTHENTICATION SCRIPT (`login.js`) *******************
 *
 * New Topics Covered in Day 21:
 * - Handling Login Form Submissions (`loginForm.addEventListener("submit", ...)`)
 * - Sending POST Login Requests with JSON Credentials (`fetch("http://localhost:8000/api/login")`)
 * - Client-Side Token Storage using Browser `localStorage` (`localStorage.setItem("token", res.user.token)`)
 * - Client-Side Page Navigation (`window.location.href = "user.html"`)
 * - Displaying dynamic notification toasts based on HTTP response success/failure
 *
 * Cross-File & Architecture References:
 * - Backend API Target: Hits `POST http://localhost:8000/api/login` (handled by `controller/user.controller.js` -> `userLogin`)
 * - Token Lifecyle: Receives `token` generated by `jwt.sign()` in backend, stores in `localStorage`, 
 *   and provides it to `user.js` for authenticated GET requests.
 *******************************************************************************************************/

// =========================================================================================
// REGISTRATION FORM SUBMISSION HANDLER (Existing from Day 19)
// =========================================================================================
const registrationForm = document.getElementById('registerForm');

registrationForm.addEventListener("submit", async (e) => {
    e.preventDefault();

    const fullName = document.getElementById("registerName").value;
    const email = document.getElementById("registerEmail").value;
    const password = document.getElementById("registerPassword").value;
    const phoneNumber = document.getElementById("registerPhone").value;

    const userData = {
        fullName, email, password, phoneNumber
    }

    const response = await fetch("http://localhost:8000/api/registration", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(userData)
    });

    const res = await response.json();

    if (res.ok) {
        Toastify({
            text: res.message,
            duration: 3000,
            destination: "https://github.com/apvarun/toastify-js",
            newWindow: true,
            close: true,
            gravity: "top",
            position: "right",
            stopOnFocus: true,
            style: {
                background: "linear-gradient(to right, #00b09b, #96c93d)",
            },
            onClick: function () { }
        }).showToast();
    } else {
        Toastify({
            text: res.message,
            duration: 3000,
            destination: "https://github.com/apvarun/toastify-js",
            newWindow: true,
            close: true,
            gravity: "top",
            position: "left",
            stopOnFocus: true,
            style: {
                background: "linear-gradient(to right, #b00000, #460404)",
            },
            onClick: function () { }
        }).showToast();
    }

})

// =========================================================================================
// [NEW IN DAY 21] LOGIN FORM SUBMISSION HANDLER
// =========================================================================================
const loginForm = document.getElementById('loginForm');

loginForm.addEventListener("submit", async (e) => {
    // 1. Prevent default form submit action (reloading the browser page)
    e.preventDefault();

    // 2. Capture user inputs from HTML login inputs (`loginEmail`, `loginPassword`)
    const email = document.getElementById("loginEmail").value;
    const password = document.getElementById("loginPassword").value;

    const userData = {
        email, password
    }

    /*
    3. Send HTTP POST request to backend server login API endpoint (`http://localhost:8000/api/login`)
       - Header `"Content-Type": "application/json"` tells Express `express.json()` middleware to parse body as JSON.
       - `JSON.stringify(userData)` converts JavaScript object into raw JSON string.
    */
    try {
        const response = await fetch("http://localhost:8000/api/login", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(userData)
        });

        // 4. Parse the JSON response received from backend `userLogin` controller
        const res = await response.json();

        if (response.ok && res.user) {
            /*
            5. CLIENT-SIDE TOKEN & USER PERSISTENCE (`localStorage`)
               Save user details and JWT token only when login is successful!
            */
            localStorage.setItem("user", JSON.stringify(res.user));
            localStorage.setItem("token", res.user.token || res.user.user?.token);

            window.location.href = "user.html";
            
            // Show success notification toast
            Toastify({
                text: res.message || "Login successful!",
                duration: 3000,
                close: true,
                gravity: "top",
                position: "right",
                style: {
                    background: "linear-gradient(to right, #00b09b, #96c93d)",
                }
            }).showToast();
        } else {
            // Show failure notification toast
            Toastify({
                text: res.message || "Login failed!",
                duration: 3000,
                close: true,
                gravity: "top",
                position: "left",
                style: {
                    background: "linear-gradient(to right, #b00000, #460404)",
                }
            }).showToast();
        }
    } catch (err) {
        console.error("Login Error:", err);
        Toastify({
            text: "Server error or connection failed!",
            duration: 3000,
            close: true,
            gravity: "top",
            position: "left",
            style: {
                background: "linear-gradient(to right, #b00000, #460404)",
            }
        }).showToast();
    }
});